```{r}
library(tidyverse)
library(ggplot2)

# Load dataset
load("data.rda")

# See objects
ls()

# Assign correct dataset
drug_data <- da36536.0001

# Inspect
glimpse(drug_data)
summary(drug_data)


# Create any drug use var to represent users of any drug in the dataset
drug_data <- drug_data |>
  mutate(
    any_drug_use = ifelse(
      CANNABIS != "CL0" | COKE != "CL0" | ECSTASY != "CL0",
      "User", "Non-user"
    )
  )
```

```{r}
# Create plot examining gender and drug use
ggplot(drug_data, aes(x = GENDER, fill = any_drug_use)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "Overall Drug Usage by Gender",
    x = "Gender",
    y = "Percent",
    fill = "Drug Usage"
  ) +
  theme_minimal()

```

```{r}
# Create plot examining education and drug use
ggplot(drug_data, aes(x = EDUCATION, fill = any_drug_use)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "Overall Drug Usage by Education Level",
    x = "Education Level",
    y = "Percent",
    fill = "Drug Usage"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
# Create plot examining age and drug use
ggplot(drug_data, aes(x = AGE, fill = any_drug_use)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  scale_x_discrete(labels = c(
    "Ag1" = "18-24",
    "Ag2" = "25 -34", 
    "Ag3" = "35 - 44", 
    "Ag4" = "45 - 54", 
    "Ag5" = "55 - 64", 
    "Ag6" = "65+"
  )) +
  labs(
    title = "Overall Drug Usage by Age",
    x = "Age Range",
    y = "Percent",
    fill = "Drug Use"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```